/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DrawId = IDL.Nat;
export const Time = IDL.Int;
export const Draw = IDL.Record({
  'id' : DrawId,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'settled' : IDL.Nat,
    'open' : IDL.Null,
  }),
  'createdAt' : Time,
});
export const BetId = IDL.Nat;
export const Bet = IDL.Record({
  'player' : IDL.Principal,
  'number' : IDL.Nat,
  'timestamp' : Time,
  'betId' : BetId,
  'amount' : IDL.Nat,
  'drawId' : DrawId,
});
export const Transaction = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'transactionType' : IDL.Variant({
    'bet' : IDL.Record({ 'betId' : BetId, 'amount' : IDL.Nat }),
    'deposit' : IDL.Record({ 'upiRef' : IDL.Text, 'amount' : IDL.Nat }),
    'withdrawal' : IDL.Record({ 'upiId' : IDL.Text, 'amount' : IDL.Nat }),
    'payout' : IDL.Record({ 'betId' : BetId, 'amount' : IDL.Nat }),
  }),
  'rejectionReason' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'transactionId' : TransactionId,
});
export const UserProfilePublic = IDL.Record({ 'userId' : IDL.Nat, 'wallet' : IDL.Nat });
export const UserProfileAdmin = IDL.Record({
  'user' : IDL.Principal,
  'userId' : IDL.Nat,
  'wallet' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'approveTransaction' : IDL.Func([TransactionId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeDraw' : IDL.Func([DrawId], [], []),
  'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [TransactionId], []),
  'createWithdrawalRequest' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [TransactionId],
      [],
    ),
  'deductBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'getActiveDraw' : IDL.Func([], [IDL.Opt(Draw)], ['query']),
  'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileAdmin)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getCallerBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDrawHistory' : IDL.Func([], [IDL.Vec(Draw)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserByUserId' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfileAdmin)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([DrawId, IDL.Nat, IDL.Nat], [BetId], []),
  'rejectTransaction' : IDL.Func([TransactionId], [], []),
  'rejectTransactionWithReason' : IDL.Func([TransactionId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfilePublic], undefined, []),
  'settleDraw' : IDL.Func([DrawId, IDL.Nat], [], []),
  'startDraw' : IDL.Func([], [DrawId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DrawId = IDL.Nat;
  const Time = IDL.Int;
  const Draw = IDL.Record({
    'id' : DrawId,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'settled' : IDL.Nat,
      'open' : IDL.Null,
    }),
    'createdAt' : Time,
  });
  const BetId = IDL.Nat;
  const Bet = IDL.Record({
    'player' : IDL.Principal,
    'number' : IDL.Nat,
    'timestamp' : Time,
    'betId' : BetId,
    'amount' : IDL.Nat,
    'drawId' : DrawId,
  });
  const Transaction = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'transactionType' : IDL.Variant({
      'bet' : IDL.Record({ 'betId' : BetId, 'amount' : IDL.Nat }),
      'deposit' : IDL.Record({ 'upiRef' : IDL.Text, 'amount' : IDL.Nat }),
      'withdrawal' : IDL.Record({ 'upiId' : IDL.Text, 'amount' : IDL.Nat }),
      'payout' : IDL.Record({ 'betId' : BetId, 'amount' : IDL.Nat }),
    }),
    'rejectionReason' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'transactionId' : TransactionId,
  });
  const UserProfilePublic = IDL.Record({ 'userId' : IDL.Nat, 'wallet' : IDL.Nat });
  const UserProfileAdmin = IDL.Record({
    'user' : IDL.Principal,
    'userId' : IDL.Nat,
    'wallet' : IDL.Nat,
  });
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'approveTransaction' : IDL.Func([TransactionId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeDraw' : IDL.Func([DrawId], [], []),
    'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [TransactionId], []),
    'createWithdrawalRequest' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [TransactionId],
        [],
      ),
    'deductBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getActiveDraw' : IDL.Func([], [IDL.Opt(Draw)], ['query']),
    'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileAdmin)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getCallerBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDrawHistory' : IDL.Func([], [IDL.Vec(Draw)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserByUserId' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfileAdmin)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([DrawId, IDL.Nat, IDL.Nat], [BetId], []),
    'rejectTransaction' : IDL.Func([TransactionId], [], []),
    'rejectTransactionWithReason' : IDL.Func([TransactionId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfilePublic], undefined, []),
    'settleDraw' : IDL.Func([DrawId, IDL.Nat], [], []),
    'startDraw' : IDL.Func([], [DrawId], []),
  });
};

export const init = ({ IDL }) => { return []; };
