/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'player' : Principal,
  'number' : bigint,
  'timestamp' : Time,
  'betId' : BetId,
  'amount' : bigint,
  'drawId' : DrawId,
}
export type BetId = bigint;
export interface Draw {
  'id' : DrawId,
  'status' : { 'closed' : null } |
    { 'settled' : bigint } |
    { 'open' : null },
  'createdAt' : Time,
}
export type DrawId = bigint;
export type Time = bigint;
export interface Transaction {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'transactionType' : { 'bet' : { 'betId' : BetId, 'amount' : bigint } } |
    { 'deposit' : { 'upiRef' : string, 'amount' : bigint } } |
    { 'withdrawal' : { 'upiId' : string, 'amount' : bigint } } |
    { 'payout' : { 'betId' : BetId, 'amount' : bigint } },
  'rejectionReason' : [] | [string],
  'user' : Principal,
  'timestamp' : Time,
  'transactionId' : TransactionId,
}
export type TransactionId = bigint;
export interface UserProfilePublic { 'userId' : bigint, 'wallet' : bigint }
export interface UserProfileAdmin { 'user' : Principal, 'userId' : bigint, 'wallet' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveTransaction' : ActorMethod<[TransactionId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeDraw' : ActorMethod<[DrawId], undefined>,
  'createDepositRequest' : ActorMethod<[bigint, string], TransactionId>,
  'createWithdrawalRequest' : ActorMethod<[bigint, string], TransactionId>,
  'deductBalance' : ActorMethod<[Principal, bigint], undefined>,
  'getActiveDraw' : ActorMethod<[], [] | [Draw]>,
  'getAllBets' : ActorMethod<[], Array<Bet>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileAdmin>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerBets' : ActorMethod<[], Array<Bet>>,
  'getCallerTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDrawHistory' : ActorMethod<[], Array<Draw>>,
  'getPendingRequests' : ActorMethod<[], Array<Transaction>>,
  'getUserByUserId' : ActorMethod<[bigint], [] | [UserProfileAdmin]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[DrawId, bigint, bigint], BetId>,
  'rejectTransaction' : ActorMethod<[TransactionId], undefined>,
  'rejectTransactionWithReason' : ActorMethod<[TransactionId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfilePublic], undefined>,
  'settleDraw' : ActorMethod<[DrawId, bigint], undefined>,
  'startDraw' : ActorMethod<[], DrawId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
