/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BetId = bigint;
export type TransactionId = bigint;
export type Time = bigint;
export interface Bet {
    player: Principal;
    number: bigint;
    timestamp: Time;
    betId: BetId;
    amount: bigint;
    drawId: DrawId;
}
export interface Draw {
    id: DrawId;
    status: {
        __kind__: "closed";
        closed: null;
    } | {
        __kind__: "settled";
        settled: bigint;
    } | {
        __kind__: "open";
        open: null;
    };
    createdAt: Time;
}
export interface UserProfileAdmin {
    userId: bigint;
    isBlocked: boolean;
    user: Principal;
    wallet: bigint;
}
export type DrawId = bigint;
export interface UserProfilePublic {
    userId: bigint;
    wallet: bigint;
}
export interface Transaction {
    status: Variant_pending_approved_rejected;
    transactionType: {
        __kind__: "bet";
        bet: {
            betId: BetId;
            amount: bigint;
        };
    } | {
        __kind__: "deposit";
        deposit: {
            upiRef: string;
            amount: bigint;
        };
    } | {
        __kind__: "withdrawal";
        withdrawal: {
            upiId: string;
            amount: bigint;
        };
    } | {
        __kind__: "payout";
        payout: {
            betId: BetId;
            amount: bigint;
        };
    };
    user: Principal;
    rejectionReason?: string;
    timestamp: Time;
    transactionId: TransactionId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBalance(user: Principal, amount: bigint): Promise<void>;
    approveTransaction(transactionId: TransactionId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    closeDraw(drawId: DrawId): Promise<void>;
    createDepositRequest(amount: bigint, upiRef: string): Promise<TransactionId>;
    createWithdrawalRequest(amount: bigint, upiId: string): Promise<TransactionId>;
    deductBalance(user: Principal, amount: bigint): Promise<void>;
    deleteDraw(drawId: DrawId): Promise<void>;
    getActiveDraw(): Promise<Draw | null>;
    getAllBets(): Promise<Array<Bet>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUserProfiles(): Promise<Array<UserProfileAdmin>>;
    getBalance(user: Principal): Promise<bigint>;
    getCallerBets(): Promise<Array<Bet>>;
    getCallerTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDrawHistory(): Promise<Array<Draw>>;
    getPendingRequests(): Promise<Array<Transaction>>;
    getUserBets(user: Principal): Promise<Array<Bet>>;
    getUserByUserId(userId: bigint): Promise<UserProfileAdmin | null>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    getUserTransactions(user: Principal): Promise<Array<Transaction>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerBlocked(): Promise<boolean>;
    placeBet(drawId: DrawId, number: bigint, amount: bigint): Promise<BetId>;
    rejectBet(betId: BetId): Promise<void>;
    rejectTransaction(transactionId: TransactionId): Promise<void>;
    rejectTransactionWithReason(transactionId: TransactionId, reason: string): Promise<void>;
    saveCallerUserProfile(arg0: UserProfilePublic): Promise<void>;
    settleDraw(drawId: DrawId, winningNumber: bigint): Promise<void>;
    startDraw(): Promise<DrawId>;
    unblockUser(user: Principal): Promise<void>;
}
import type { BetId as _BetId, Draw as _Draw, DrawId as _DrawId, Time as _Time, Transaction as _Transaction, TransactionId as _TransactionId, UserProfileAdmin as _UserProfileAdmin, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBalance(arg0, arg1);
            return result;
        }
    }
    async approveTransaction(arg0: TransactionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTransaction(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async closeDraw(arg0: DrawId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeDraw(arg0);
            return result;
        }
    }
    async createDepositRequest(arg0: bigint, arg1: string): Promise<TransactionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepositRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepositRequest(arg0, arg1);
            return result;
        }
    }
    async createWithdrawalRequest(arg0: bigint, arg1: string): Promise<TransactionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async deductBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deductBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductBalance(arg0, arg1);
            return result;
        }
    }
    async deleteDraw(arg0: DrawId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraw(arg0);
            return result;
        }
    }
    async getActiveDraw(): Promise<Draw | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDraw();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDraw();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBets();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfileAdmin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return result;
        }
    }
    async getCallerBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBets();
            return result;
        }
    }
    async getCallerTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrawHistory(): Promise<Array<Draw>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrawHistory();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrawHistory();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRequests(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBets(arg0: Principal): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBets(arg0);
            return result;
        }
    }
    async getUserByUserId(arg0: bigint): Promise<UserProfileAdmin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUserId(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUserId(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerBlocked(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerBlocked();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerBlocked();
            return result;
        }
    }
    async placeBet(arg0: DrawId, arg1: bigint, arg2: bigint): Promise<BetId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectBet(arg0: BetId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBet(arg0);
            return result;
        }
    }
    async rejectTransaction(arg0: TransactionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTransaction(arg0);
            return result;
        }
    }
    async rejectTransactionWithReason(arg0: TransactionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTransactionWithReason(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTransactionWithReason(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfilePublic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async settleDraw(arg0: DrawId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.settleDraw(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleDraw(arg0, arg1);
            return result;
        }
    }
    async startDraw(): Promise<DrawId> {
        if (this.processError) {
            try {
                const result = await this.actor.startDraw();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startDraw();
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
}
function from_candid_Draw_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Draw): Draw {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileAdmin]): UserProfileAdmin | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Draw]): Draw | null {
    return value.length === 0 ? null : from_candid_Draw_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DrawId;
    status: {
        closed: null;
    } | {
        settled: bigint;
    } | {
        open: null;
    };
    createdAt: _Time;
}): {
    id: DrawId;
    status: {
        __kind__: "closed";
        closed: null;
    } | {
        __kind__: "settled";
        settled: bigint;
    } | {
        __kind__: "open";
        open: null;
    };
    createdAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    transactionType: {
        bet: {
            betId: _BetId;
            amount: bigint;
        };
    } | {
        deposit: {
            upiRef: string;
            amount: bigint;
        };
    } | {
        withdrawal: {
            upiId: string;
            amount: bigint;
        };
    } | {
        payout: {
            betId: _BetId;
            amount: bigint;
        };
    };
    user: Principal;
    rejectionReason: [] | [string];
    timestamp: _Time;
    transactionId: _TransactionId;
}): {
    status: Variant_pending_approved_rejected;
    transactionType: {
        __kind__: "bet";
        bet: {
            betId: BetId;
            amount: bigint;
        };
    } | {
        __kind__: "deposit";
        deposit: {
            upiRef: string;
            amount: bigint;
        };
    } | {
        __kind__: "withdrawal";
        withdrawal: {
            upiId: string;
            amount: bigint;
        };
    } | {
        __kind__: "payout";
        payout: {
            betId: BetId;
            amount: bigint;
        };
    };
    user: Principal;
    rejectionReason?: string;
    timestamp: Time;
    transactionId: TransactionId;
} {
    return {
        status: from_candid_variant_n10(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_variant_n11(_uploadFile, _downloadFile, value.transactionType),
        user: value.user,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.rejectionReason)),
        timestamp: value.timestamp,
        transactionId: value.transactionId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bet: {
        betId: _BetId;
        amount: bigint;
    };
} | {
    deposit: {
        upiRef: string;
        amount: bigint;
    };
} | {
    withdrawal: {
        upiId: string;
        amount: bigint;
    };
} | {
    payout: {
        betId: _BetId;
        amount: bigint;
    };
}): {
    __kind__: "bet";
    bet: {
        betId: BetId;
        amount: bigint;
    };
} | {
    __kind__: "deposit";
    deposit: {
        upiRef: string;
        amount: bigint;
    };
} | {
    __kind__: "withdrawal";
    withdrawal: {
        upiId: string;
        amount: bigint;
    };
} | {
    __kind__: "payout";
    payout: {
        betId: BetId;
        amount: bigint;
    };
} {
    return "bet" in value ? {
        __kind__: "bet",
        bet: value.bet
    } : "deposit" in value ? {
        __kind__: "deposit",
        deposit: value.deposit
    } : "withdrawal" in value ? {
        __kind__: "withdrawal",
        withdrawal: value.withdrawal
    } : "payout" in value ? {
        __kind__: "payout",
        payout: value.payout
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    settled: bigint;
} | {
    open: null;
}): {
    __kind__: "closed";
    closed: null;
} | {
    __kind__: "settled";
    settled: bigint;
} | {
    __kind__: "open";
    open: null;
} {
    return "closed" in value ? {
        __kind__: "closed",
        closed: value.closed
    } : "settled" in value ? {
        __kind__: "settled",
        settled: value.settled
    } : "open" in value ? {
        __kind__: "open",
        open: value.open
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Draw>): Array<Draw> {
    return value.map((x)=>from_candid_Draw_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
